### ISSUE TITLE
Common MD validation for fronted and backend

### ISSUE THREAD

**Issue by rhoerbe** [Emergya/peer#55]
Hi Leif, we talked about this at #TNC2014:

My requirement is to add custom MD validators (including a profile from saml_schematron project). To make this usable, PEER should use only a single MD validator (settings.py/METADATA_VALIDATORS), not separate ones in Javascript and Django. 
In this context all responses from the validator should be displayed, which would require a scrollable list.

**Comment by enriquepablo** [comment]
Right now, there is validation in both the frontend and backend, but they do not collide. In the frontend the details of the metadata are validated in the md editor, the attribute values and child elements etc. In the backend the whole xml doc is validated against a configurable list of validators. There has been a discussion on this in the mailing list and the conclussion has been that the present situation is correct.

**Comment by rhoerbe** [comment]
I do not remember that we agreed on this. Finally, it is a bug in the architecture allowing to configure varying rules in the back-end, with not feasible path to align this with the front-end. From the TCO perspective, the first change in schema validation is already justifying the removal of front-end validation code.

**Comment by enriquepablo** [comment]
@rhoerbe: I am not sure where is it that we disagree, so I'll try to be as
explicit as possible with my view of things.

We want to have a javascript MD editor, in which we want to be able to edit
the MD doc in the raw, in a simple text area, and have changes in the raw
view show up in the tree view; And likewise, edit it piecewise in a tree,
and have changes made in the tree view show up in the raw view. For this,
we need to parse the MD document. We can do this parsing in the backend;
send to the backend every single edit in both views, so that the backend
processes, validates, and builds both representations of the MD doc (raw
and tree) to send back to the browser. This (having a minimum of a round
trip to the server for each editing action) would make for a very poor user
experience. What makes sense, in my opinion, is to parse in the browser.
And if there are parsing errors, you want to show them. Validation is an
natural part of parsing. Hiding any parsing/validation errors because they
happen to arise in the browser would not make sense.
Now, we must also validate in the backend. There are some checks that need
access to the db or to some other services that are not accessible from the
browser. And to validate, we need to parse. So yes, we parse both in the
browser and in the server, and thus have 2 different sources of validation
and parsing errors. But imho this makes sense both from an UX point of view
and architecturally. There is a clear separation of concerns between the 2
validation realms. In the server, the whole document is checked as well
formed xml and valid against a very complex xsd. This needs big libraries,
more readily available in the server. But from an UX point of view it is
not too bad, since validating the doc as a whole only has to happen when it
is saved, and the user expects some delay after clicking "save". In the
browser, we check the constraints that are specific for the business logic
that drives the editor. Those make for lighter code that fits well in js
sent over the wire. And then we have the odd constraint that needs acces to
the db or similar, and has to be delegated to the backend; and these are
the most detrimental to the UX.

I agree that this double abstraction may have leaks, for example when the
simpler and more specific parser in the browser does not understand some
element (the parser in the backend would always allow for a perfect tree).
But having the js editor delegate the handling of every single editing
event to the backend would be quite worse.

2015-10-07 15:17 GMT+02:00 Rainer Hörbe <notifications@github.com>:

> I do not remember that we agreed on this. Finally, it is a bug in the
> architecture allowing to configure varying rules in the back-end, with not
> feasible path to align this with the front-end. From the TCO perspective,
> the first change in schema validation is already justifying the removal of
> front-end validation code.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Emergya/peer/issues/55#issuecomment-146193532>.
>



-- 
Enrique Pérez Arnaud
enrique@cazalla.net

**Comment by rhoerbe** [comment]
You are right. I recall that my initial concern was about a strange sequence of error and warning messages. But I agree with your explanation.
